### ISSUE TITLE
How does the EOS BP voting process reach consensus?

### ISSUE THREAD

**Issue by r3db** [EOSIO/Documentation#102]
I'm curious about the voting process. Wondering if anyone could clarify or point me in the right direction.
The documentation does not seem to be very clear on this topic

Multiple nodes are constantly receiving/losing votes. The top 21 are selected as BPs. How do we reach consensus on the BPs, I mean, votes take time to propagate, thus different nodes have different views of the world. How does EOS reconcile this information?

Let me further clarify, when processing transactions a BP emits a block with let's say 500 tx.

It's ok if your transaction was not processed at this point in time, it will probably be picked up in the next few minutes. Furthermore other BPs can easily validate the block, (the only thing a BP is interested is to prevent fraudulent txs).

Voting is different. **Every vote counts**, (I assume), since it takes time for information to propagate different BPs will have different views of the world.

How do BPs decide what is the correct vote count at a specific point in time when the voting process itself is so active?

**Comment by lazaridiscom** [comment]
General Remark: questions like this are better placed on stackexchange / reddit.

Some answers to this can be found here:

https://eosio.stackexchange.com/a/1520

https://www.reddit.com/r/eos/comments/8x31ge/how_does_the_eos_bp_voting_process_reach_consensus/e20ix3f/

@r3db , you can close the issue if you got the answer.
