### ISSUE TITLE
Image in whitepaper doesn't display

### ISSUE THREAD

**Issue by jamesray1** [EOSIO/Documentation#25]
In the Whitepaper, the second image under https://github.com/EOSIO/Documentation/blob/master/TechnicalWhitePaper.md#evaluating-permissions
doesn't display.

**Comment by andrewbaine** [comment]
I am evaluating EOS and this reflects poorly; several images do not display correctly in the whitepaper. You are very likely losing people whose curiosity is piqued but then determine the project is not well maintained if they can't even read the whitepaper

**Comment by str** [comment]
@jamesray1 can you confirm it's fixed now?

**Comment by jamesray1** [comment]
Yes, it's fixed.
