### ISSUE TITLE
在此立贴，明年6月份EOS 价格翻10倍

### ISSUE THREAD

**Issue by yca2220206** [EOSIO/Documentation#36]
在此立贴，明年6月份EOS 价格翻10倍

                                                     by罗聪

**Comment by freeloda** [comment]
支持！

**Comment by zhongyitrip** [comment]
我也跟帖 立贴  20倍。今天47.

**Comment by Bintong** [comment]
那卖的人都是怎么想的

**Comment by chenlocus** [comment]
我最看好eos的，但是我也在此立贴：明年底前价格在 现在基础上腰斩：）

**Comment by yca2220206** [comment]
Upstairs please hit your own face by the end of this year, @chenlocus , Also please eos development team to speed up the development progress, you do not update the code half a month, and our investors are waiting for you, applause and cheer for you.

**Comment by huyang168** [comment]
至少翻十倍，跟着你们玩

**Comment by yca2220206** [comment]
已经10美元了，再不上车你们没机会了

**Comment by Bintong** [comment]
目标价格500

**Comment by yangzongquan** [comment]
Ethereum这么烂的东西市值能上100B，EOS市值能轻松上100B，所以第一目标价是$100。

**Comment by yangzongquan** [comment]
第二阶段是等着EOS平台上商业应用大爆发，目标市值是苹果，可能也就一两年的时间...

**Comment by jackadams324** [comment]
为什么有这种自信呢？今天才上车的。

**Comment by yca2220206** [comment]
@jackadams324 看看国内的垃圾币，就一张白皮书，稍微好点的就再多一个网站，里面几张图片和一些文字，吹得天花乱坠 ,具体请看唯币 https://www.vechain.com/#/   ,都能和奢侈品扯上关系，真够恶心的，圈钱圈出牌坊来了， 这些拿不出实际项目的空气币、垃圾币能和eos比么。3年后eos还在，其他那些垃圾币早就圈钱跑人了。

**Comment by zw0** [comment]
issues不是这么用的，丢人

**Comment by Stevengu999** [comment]
不要光想着钱，还是要看应用的价值。看看你会用这个神器来做什么。

**Comment by TzyTman** [comment]
还是看中价值比较好

**Comment by zw0** [comment]
也可能玩完哈哈

**Comment by zw0** [comment]
看好ada  https://github.com/input-output-hk/cardano-sl

**Comment by chenjinya** [comment]
你们看懂白皮书了？？

**Comment by zw0** [comment]
没有

**Comment by chenjinya** [comment]
竟然被close了。。。
