### ISSUE TITLE
Italian Translations

### ISSUE THREAD

**Issue by digitalplayer-steemit** [EOSIO/Documentation#49]
Hello

My name is Michael Asumcinei and I would like to contribute with Italian translations.

I can do that only using Github as I am an adopter of Utopian.io project to reward open source software.

Just let me know if you are interested and I will be there for it

Best Regards
Michael Asumcinei
steemit.com/@digitalplayer

**Comment by gleehokie** [comment]
Yes, we are open to new translations.  Note that there is a pull request on the technical white paper that is waiting for acceptance.
