### ISSUE TITLE
search eos news

### ISSUE THREAD

**Issue by Ultraman95** [EOSIO/Documentation#85]
[www.google.com](url)

**Comment by shilf** [comment]
[https://www.google.com.hk/webhp?hl=zh-CN&sourceid=cnhp](url)

**Comment by shilf** [comment]
https://www.google.com/

**Comment by shilf** [comment]
https//www.bing.com

**Comment by shilf** [comment]
[https//www.bing.com](url)

**Comment by shilf** [comment]
https://www.bing.com
